### ISSUE TITLE
Hover not working in dark mode

### ISSUE THREAD

**Issue by shriya030** [himanshu007-creator/SFC-foundations#360] opened 2021-05-29 22:39 UTC
## Issue Type:
[ x ] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Except in the Events and News section, hover is not working on any of the buttons in dark mode.

## **Possible solution**

I would like to change the color of buttons in dark mode to yellow upon hovering.

## **Screenshots**

![image](https://user-images.githubusercontent.com/56861600/120086460-ce474180-c0fc-11eb-8907-b7cc48c54750.png)

**Comment by shriya030** [comment] 2021-05-29 22:40
@himanshu007-creator Can I work on this?

**Comment by rohank2502** [comment] 2021-05-30 05:08
Duplicate of #330

**Comment by himanshu007-creator** [comment] 2021-05-30 05:21
Closed in favor of #330

**Closed by himanshu007-creator** 2021-05-30 05:21 UTC
